// Code generated by /tmp/gen_weaviateserver_methods.go; DO NOT EDIT.

package weaviateserver

import (
	"errors"
	"fmt"
	opsroot "github.com/weaviate/weaviate/adapters/handlers/rest/operations"
	opsauthz "github.com/weaviate/weaviate/adapters/handlers/rest/operations/authz"
	opsbackups "github.com/weaviate/weaviate/adapters/handlers/rest/operations/backups"
	opsbatch "github.com/weaviate/weaviate/adapters/handlers/rest/operations/batch"
	opsclassifications "github.com/weaviate/weaviate/adapters/handlers/rest/operations/classifications"
	opscluster "github.com/weaviate/weaviate/adapters/handlers/rest/operations/cluster"
	opsdistributed_tasks "github.com/weaviate/weaviate/adapters/handlers/rest/operations/distributed_tasks"
	opsexport "github.com/weaviate/weaviate/adapters/handlers/rest/operations/export"
	opsgraphql "github.com/weaviate/weaviate/adapters/handlers/rest/operations/graphql"
	opsmeta "github.com/weaviate/weaviate/adapters/handlers/rest/operations/meta"
	opsnodes "github.com/weaviate/weaviate/adapters/handlers/rest/operations/nodes"
	opsobjects "github.com/weaviate/weaviate/adapters/handlers/rest/operations/objects"
	opsreplication "github.com/weaviate/weaviate/adapters/handlers/rest/operations/replication"
	opsschema "github.com/weaviate/weaviate/adapters/handlers/rest/operations/schema"
	opsusers "github.com/weaviate/weaviate/adapters/handlers/rest/operations/users"
	opswell_known "github.com/weaviate/weaviate/adapters/handlers/rest/operations/well_known"
)

// WeaviateRoot 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) WeaviateRoot(params opsroot.WeaviateRootParams) (*opsroot.WeaviateRootOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.WeaviateRootHandler == nil {
		return nil, errors.New("weaviateroot handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "GET", "/v1")
	}

	responder := ws.api.WeaviateRootHandler.Handle(params, nil)

	if ok, success := responder.(*opsroot.WeaviateRootOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("WeaviateRoot failed: responder=%T", responder)
}

// WeaviateWellknownLiveness 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) WeaviateWellknownLiveness(params opsroot.WeaviateWellknownLivenessParams) (*opsroot.WeaviateWellknownLivenessOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.WeaviateWellknownLivenessHandler == nil {
		return nil, errors.New("weaviatewellknownliveness handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "GET", "/v1/.well-known/live")
	}

	responder := ws.api.WeaviateWellknownLivenessHandler.Handle(params, nil)

	if ok, success := responder.(*opsroot.WeaviateWellknownLivenessOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("WeaviateWellknownLiveness failed: responder=%T", responder)
}

// WeaviateWellknownReadiness 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) WeaviateWellknownReadiness(params opsroot.WeaviateWellknownReadinessParams) (*opsroot.WeaviateWellknownReadinessOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.WeaviateWellknownReadinessHandler == nil {
		return nil, errors.New("weaviatewellknownreadiness handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "GET", "/v1/.well-known/ready")
	}

	responder := ws.api.WeaviateWellknownReadinessHandler.Handle(params, nil)

	if ok, success := responder.(*opsroot.WeaviateWellknownReadinessOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("WeaviateWellknownReadiness failed: responder=%T", responder)
}

// AddPermissions 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) AddPermissions(params opsauthz.AddPermissionsParams) (*opsauthz.AddPermissionsOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.AuthzAddPermissionsHandler == nil {
		return nil, errors.New("authzaddpermissions handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "POST", "/v1/authz/roles/{id}/add-permissions")
	}

	responder := ws.api.AuthzAddPermissionsHandler.Handle(params, nil)

	if ok, success := responder.(*opsauthz.AddPermissionsOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("AddPermissions failed: responder=%T", responder)
}

// AssignRoleToGroup 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) AssignRoleToGroup(params opsauthz.AssignRoleToGroupParams) (*opsauthz.AssignRoleToGroupOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.AuthzAssignRoleToGroupHandler == nil {
		return nil, errors.New("authzassignroletogroup handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "POST", "/v1/authz/groups/{id}/assign")
	}

	responder := ws.api.AuthzAssignRoleToGroupHandler.Handle(params, nil)

	if ok, success := responder.(*opsauthz.AssignRoleToGroupOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("AssignRoleToGroup failed: responder=%T", responder)
}

// AssignRoleToUser 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) AssignRoleToUser(params opsauthz.AssignRoleToUserParams) (*opsauthz.AssignRoleToUserOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.AuthzAssignRoleToUserHandler == nil {
		return nil, errors.New("authzassignroletouser handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "POST", "/v1/authz/users/{id}/assign")
	}

	responder := ws.api.AuthzAssignRoleToUserHandler.Handle(params, nil)

	if ok, success := responder.(*opsauthz.AssignRoleToUserOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("AssignRoleToUser failed: responder=%T", responder)
}

// CreateRole 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) CreateRole(params opsauthz.CreateRoleParams) (*opsauthz.CreateRoleCreated, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.AuthzCreateRoleHandler == nil {
		return nil, errors.New("authzcreaterole handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "POST", "/v1/authz/roles")
	}

	responder := ws.api.AuthzCreateRoleHandler.Handle(params, nil)

	if ok, success := responder.(*opsauthz.CreateRoleCreated); success {
		return ok, nil
	}

	return nil, fmt.Errorf("CreateRole failed: responder=%T", responder)
}

// DeleteRole 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) DeleteRole(params opsauthz.DeleteRoleParams) (*opsauthz.DeleteRoleNoContent, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.AuthzDeleteRoleHandler == nil {
		return nil, errors.New("authzdeleterole handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "DELETE", "/v1/authz/roles/{id}")
	}

	responder := ws.api.AuthzDeleteRoleHandler.Handle(params, nil)

	if ok, success := responder.(*opsauthz.DeleteRoleNoContent); success {
		return ok, nil
	}

	return nil, fmt.Errorf("DeleteRole failed: responder=%T", responder)
}

// GetGroups 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) GetGroups(params opsauthz.GetGroupsParams) (*opsauthz.GetGroupsOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.AuthzGetGroupsHandler == nil {
		return nil, errors.New("authzgetgroups handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "GET", "/v1/authz/groups/{groupType}")
	}

	responder := ws.api.AuthzGetGroupsHandler.Handle(params, nil)

	if ok, success := responder.(*opsauthz.GetGroupsOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("GetGroups failed: responder=%T", responder)
}

// GetGroupsForRole 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) GetGroupsForRole(params opsauthz.GetGroupsForRoleParams) (*opsauthz.GetGroupsForRoleOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.AuthzGetGroupsForRoleHandler == nil {
		return nil, errors.New("authzgetgroupsforrole handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "GET", "/v1/authz/roles/{id}/group-assignments")
	}

	responder := ws.api.AuthzGetGroupsForRoleHandler.Handle(params, nil)

	if ok, success := responder.(*opsauthz.GetGroupsForRoleOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("GetGroupsForRole failed: responder=%T", responder)
}

// GetRole 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) GetRole(params opsauthz.GetRoleParams) (*opsauthz.GetRoleOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.AuthzGetRoleHandler == nil {
		return nil, errors.New("authzgetrole handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "GET", "/v1/authz/roles/{id}")
	}

	responder := ws.api.AuthzGetRoleHandler.Handle(params, nil)

	if ok, success := responder.(*opsauthz.GetRoleOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("GetRole failed: responder=%T", responder)
}

// GetRoles 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) GetRoles(params opsauthz.GetRolesParams) (*opsauthz.GetRolesOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.AuthzGetRolesHandler == nil {
		return nil, errors.New("authzgetroles handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "GET", "/v1/authz/roles")
	}

	responder := ws.api.AuthzGetRolesHandler.Handle(params, nil)

	if ok, success := responder.(*opsauthz.GetRolesOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("GetRoles failed: responder=%T", responder)
}

// GetRolesForGroup 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) GetRolesForGroup(params opsauthz.GetRolesForGroupParams) (*opsauthz.GetRolesForGroupOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.AuthzGetRolesForGroupHandler == nil {
		return nil, errors.New("authzgetrolesforgroup handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "GET", "/v1/authz/groups/{id}/roles/{groupType}")
	}

	responder := ws.api.AuthzGetRolesForGroupHandler.Handle(params, nil)

	if ok, success := responder.(*opsauthz.GetRolesForGroupOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("GetRolesForGroup failed: responder=%T", responder)
}

// GetRolesForUser 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) GetRolesForUser(params opsauthz.GetRolesForUserParams) (*opsauthz.GetRolesForUserOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.AuthzGetRolesForUserHandler == nil {
		return nil, errors.New("authzgetrolesforuser handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "GET", "/v1/authz/users/{id}/roles/{userType}")
	}

	responder := ws.api.AuthzGetRolesForUserHandler.Handle(params, nil)

	if ok, success := responder.(*opsauthz.GetRolesForUserOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("GetRolesForUser failed: responder=%T", responder)
}

// GetRolesForUserDeprecated 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) GetRolesForUserDeprecated(params opsauthz.GetRolesForUserDeprecatedParams) (*opsauthz.GetRolesForUserDeprecatedOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.AuthzGetRolesForUserDeprecatedHandler == nil {
		return nil, errors.New("authzgetrolesforuserdeprecated handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "GET", "/v1/authz/users/{id}/roles")
	}

	responder := ws.api.AuthzGetRolesForUserDeprecatedHandler.Handle(params, nil)

	if ok, success := responder.(*opsauthz.GetRolesForUserDeprecatedOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("GetRolesForUserDeprecated failed: responder=%T", responder)
}

// GetUsersForRole 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) GetUsersForRole(params opsauthz.GetUsersForRoleParams) (*opsauthz.GetUsersForRoleOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.AuthzGetUsersForRoleHandler == nil {
		return nil, errors.New("authzgetusersforrole handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "GET", "/v1/authz/roles/{id}/user-assignments")
	}

	responder := ws.api.AuthzGetUsersForRoleHandler.Handle(params, nil)

	if ok, success := responder.(*opsauthz.GetUsersForRoleOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("GetUsersForRole failed: responder=%T", responder)
}

// GetUsersForRoleDeprecated 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) GetUsersForRoleDeprecated(params opsauthz.GetUsersForRoleDeprecatedParams) (*opsauthz.GetUsersForRoleDeprecatedOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.AuthzGetUsersForRoleDeprecatedHandler == nil {
		return nil, errors.New("authzgetusersforroledeprecated handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "GET", "/v1/authz/roles/{id}/users")
	}

	responder := ws.api.AuthzGetUsersForRoleDeprecatedHandler.Handle(params, nil)

	if ok, success := responder.(*opsauthz.GetUsersForRoleDeprecatedOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("GetUsersForRoleDeprecated failed: responder=%T", responder)
}

// HasPermission 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) HasPermission(params opsauthz.HasPermissionParams) (*opsauthz.HasPermissionOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.AuthzHasPermissionHandler == nil {
		return nil, errors.New("authzhaspermission handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "POST", "/v1/authz/roles/{id}/has-permission")
	}

	responder := ws.api.AuthzHasPermissionHandler.Handle(params, nil)

	if ok, success := responder.(*opsauthz.HasPermissionOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("HasPermission failed: responder=%T", responder)
}

// RemovePermissions 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) RemovePermissions(params opsauthz.RemovePermissionsParams) (*opsauthz.RemovePermissionsOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.AuthzRemovePermissionsHandler == nil {
		return nil, errors.New("authzremovepermissions handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "POST", "/v1/authz/roles/{id}/remove-permissions")
	}

	responder := ws.api.AuthzRemovePermissionsHandler.Handle(params, nil)

	if ok, success := responder.(*opsauthz.RemovePermissionsOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("RemovePermissions failed: responder=%T", responder)
}

// RevokeRoleFromGroup 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) RevokeRoleFromGroup(params opsauthz.RevokeRoleFromGroupParams) (*opsauthz.RevokeRoleFromGroupOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.AuthzRevokeRoleFromGroupHandler == nil {
		return nil, errors.New("authzrevokerolefromgroup handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "POST", "/v1/authz/groups/{id}/revoke")
	}

	responder := ws.api.AuthzRevokeRoleFromGroupHandler.Handle(params, nil)

	if ok, success := responder.(*opsauthz.RevokeRoleFromGroupOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("RevokeRoleFromGroup failed: responder=%T", responder)
}

// RevokeRoleFromUser 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) RevokeRoleFromUser(params opsauthz.RevokeRoleFromUserParams) (*opsauthz.RevokeRoleFromUserOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.AuthzRevokeRoleFromUserHandler == nil {
		return nil, errors.New("authzrevokerolefromuser handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "POST", "/v1/authz/users/{id}/revoke")
	}

	responder := ws.api.AuthzRevokeRoleFromUserHandler.Handle(params, nil)

	if ok, success := responder.(*opsauthz.RevokeRoleFromUserOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("RevokeRoleFromUser failed: responder=%T", responder)
}

// BackupsCancel 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) BackupsCancel(params opsbackups.BackupsCancelParams) (*opsbackups.BackupsCancelNoContent, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.BackupsBackupsCancelHandler == nil {
		return nil, errors.New("backupsbackupscancel handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "DELETE", "/v1/backups/{backend}/{id}")
	}

	responder := ws.api.BackupsBackupsCancelHandler.Handle(params, nil)

	if ok, success := responder.(*opsbackups.BackupsCancelNoContent); success {
		return ok, nil
	}

	return nil, fmt.Errorf("BackupsCancel failed: responder=%T", responder)
}

// BackupsCreate 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) BackupsCreate(params opsbackups.BackupsCreateParams) (*opsbackups.BackupsCreateOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.BackupsBackupsCreateHandler == nil {
		return nil, errors.New("backupsbackupscreate handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "POST", "/v1/backups/{backend}")
	}

	responder := ws.api.BackupsBackupsCreateHandler.Handle(params, nil)

	if ok, success := responder.(*opsbackups.BackupsCreateOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("BackupsCreate failed: responder=%T", responder)
}

// BackupsCreateStatus 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) BackupsCreateStatus(params opsbackups.BackupsCreateStatusParams) (*opsbackups.BackupsCreateStatusOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.BackupsBackupsCreateStatusHandler == nil {
		return nil, errors.New("backupsbackupscreatestatus handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "GET", "/v1/backups/{backend}/{id}")
	}

	responder := ws.api.BackupsBackupsCreateStatusHandler.Handle(params, nil)

	if ok, success := responder.(*opsbackups.BackupsCreateStatusOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("BackupsCreateStatus failed: responder=%T", responder)
}

// BackupsList 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) BackupsList(params opsbackups.BackupsListParams) (*opsbackups.BackupsListOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.BackupsBackupsListHandler == nil {
		return nil, errors.New("backupsbackupslist handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "GET", "/v1/backups/{backend}")
	}

	responder := ws.api.BackupsBackupsListHandler.Handle(params, nil)

	if ok, success := responder.(*opsbackups.BackupsListOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("BackupsList failed: responder=%T", responder)
}

// BackupsRestore 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) BackupsRestore(params opsbackups.BackupsRestoreParams) (*opsbackups.BackupsRestoreOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.BackupsBackupsRestoreHandler == nil {
		return nil, errors.New("backupsbackupsrestore handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "POST", "/v1/backups/{backend}/{id}/restore")
	}

	responder := ws.api.BackupsBackupsRestoreHandler.Handle(params, nil)

	if ok, success := responder.(*opsbackups.BackupsRestoreOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("BackupsRestore failed: responder=%T", responder)
}

// BackupsRestoreCancel 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) BackupsRestoreCancel(params opsbackups.BackupsRestoreCancelParams) (*opsbackups.BackupsRestoreCancelNoContent, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.BackupsBackupsRestoreCancelHandler == nil {
		return nil, errors.New("backupsbackupsrestorecancel handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "DELETE", "/v1/backups/{backend}/{id}/restore")
	}

	responder := ws.api.BackupsBackupsRestoreCancelHandler.Handle(params, nil)

	if ok, success := responder.(*opsbackups.BackupsRestoreCancelNoContent); success {
		return ok, nil
	}

	return nil, fmt.Errorf("BackupsRestoreCancel failed: responder=%T", responder)
}

// BackupsRestoreStatus 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) BackupsRestoreStatus(params opsbackups.BackupsRestoreStatusParams) (*opsbackups.BackupsRestoreStatusOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.BackupsBackupsRestoreStatusHandler == nil {
		return nil, errors.New("backupsbackupsrestorestatus handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "GET", "/v1/backups/{backend}/{id}/restore")
	}

	responder := ws.api.BackupsBackupsRestoreStatusHandler.Handle(params, nil)

	if ok, success := responder.(*opsbackups.BackupsRestoreStatusOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("BackupsRestoreStatus failed: responder=%T", responder)
}

// BatchObjectsCreate 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) BatchObjectsCreate(params opsbatch.BatchObjectsCreateParams) (*opsbatch.BatchObjectsCreateOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.BatchBatchObjectsCreateHandler == nil {
		return nil, errors.New("batchbatchobjectscreate handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "POST", "/v1/batch/objects")
	}

	responder := ws.api.BatchBatchObjectsCreateHandler.Handle(params, nil)

	if ok, success := responder.(*opsbatch.BatchObjectsCreateOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("BatchObjectsCreate failed: responder=%T", responder)
}

// BatchObjectsDelete 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) BatchObjectsDelete(params opsbatch.BatchObjectsDeleteParams) (*opsbatch.BatchObjectsDeleteOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.BatchBatchObjectsDeleteHandler == nil {
		return nil, errors.New("batchbatchobjectsdelete handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "DELETE", "/v1/batch/objects")
	}

	responder := ws.api.BatchBatchObjectsDeleteHandler.Handle(params, nil)

	if ok, success := responder.(*opsbatch.BatchObjectsDeleteOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("BatchObjectsDelete failed: responder=%T", responder)
}

// BatchReferencesCreate 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) BatchReferencesCreate(params opsbatch.BatchReferencesCreateParams) (*opsbatch.BatchReferencesCreateOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.BatchBatchReferencesCreateHandler == nil {
		return nil, errors.New("batchbatchreferencescreate handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "POST", "/v1/batch/references")
	}

	responder := ws.api.BatchBatchReferencesCreateHandler.Handle(params, nil)

	if ok, success := responder.(*opsbatch.BatchReferencesCreateOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("BatchReferencesCreate failed: responder=%T", responder)
}

// ClassificationsGet 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) ClassificationsGet(params opsclassifications.ClassificationsGetParams) (*opsclassifications.ClassificationsGetOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.ClassificationsClassificationsGetHandler == nil {
		return nil, errors.New("classificationsclassificationsget handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "GET", "/v1/classifications/{id}")
	}

	responder := ws.api.ClassificationsClassificationsGetHandler.Handle(params, nil)

	if ok, success := responder.(*opsclassifications.ClassificationsGetOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("ClassificationsGet failed: responder=%T", responder)
}

// ClassificationsPost 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) ClassificationsPost(params opsclassifications.ClassificationsPostParams) (*opsclassifications.ClassificationsPostCreated, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.ClassificationsClassificationsPostHandler == nil {
		return nil, errors.New("classificationsclassificationspost handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "POST", "/v1/classifications")
	}

	responder := ws.api.ClassificationsClassificationsPostHandler.Handle(params, nil)

	if ok, success := responder.(*opsclassifications.ClassificationsPostCreated); success {
		return ok, nil
	}

	return nil, fmt.Errorf("ClassificationsPost failed: responder=%T", responder)
}

// ClusterGetStatistics 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) ClusterGetStatistics(params opscluster.ClusterGetStatisticsParams) (*opscluster.ClusterGetStatisticsOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.ClusterClusterGetStatisticsHandler == nil {
		return nil, errors.New("clusterclustergetstatistics handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "GET", "/v1/cluster/statistics")
	}

	responder := ws.api.ClusterClusterGetStatisticsHandler.Handle(params, nil)

	if ok, success := responder.(*opscluster.ClusterGetStatisticsOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("ClusterGetStatistics failed: responder=%T", responder)
}

// DistributedTasksGet 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) DistributedTasksGet(params opsdistributed_tasks.DistributedTasksGetParams) (*opsdistributed_tasks.DistributedTasksGetOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.DistributedTasksDistributedTasksGetHandler == nil {
		return nil, errors.New("distributedtasksdistributedtasksget handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "GET", "/v1/tasks")
	}

	responder := ws.api.DistributedTasksDistributedTasksGetHandler.Handle(params, nil)

	if ok, success := responder.(*opsdistributed_tasks.DistributedTasksGetOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("DistributedTasksGet failed: responder=%T", responder)
}

// ExportCreate 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) ExportCreate(params opsexport.ExportCreateParams) (*opsexport.ExportCreateOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.ExportExportCreateHandler == nil {
		return nil, errors.New("exportexportcreate handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "POST", "/v1/export/{backend}")
	}

	responder := ws.api.ExportExportCreateHandler.Handle(params, nil)

	if ok, success := responder.(*opsexport.ExportCreateOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("ExportCreate failed: responder=%T", responder)
}

// ExportStatus 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) ExportStatus(params opsexport.ExportStatusParams) (*opsexport.ExportStatusOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.ExportExportStatusHandler == nil {
		return nil, errors.New("exportexportstatus handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "GET", "/v1/export/{backend}/{id}")
	}

	responder := ws.api.ExportExportStatusHandler.Handle(params, nil)

	if ok, success := responder.(*opsexport.ExportStatusOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("ExportStatus failed: responder=%T", responder)
}

// GraphqlBatch 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) GraphqlBatch(params opsgraphql.GraphqlBatchParams) (*opsgraphql.GraphqlBatchOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.GraphqlGraphqlBatchHandler == nil {
		return nil, errors.New("graphqlgraphqlbatch handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "POST", "/v1/graphql/batch")
	}

	responder := ws.api.GraphqlGraphqlBatchHandler.Handle(params, nil)

	if ok, success := responder.(*opsgraphql.GraphqlBatchOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("GraphqlBatch failed: responder=%T", responder)
}

// GraphqlPost 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) GraphqlPost(params opsgraphql.GraphqlPostParams) (*opsgraphql.GraphqlPostOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.GraphqlGraphqlPostHandler == nil {
		return nil, errors.New("graphqlgraphqlpost handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "POST", "/v1/graphql")
	}

	responder := ws.api.GraphqlGraphqlPostHandler.Handle(params, nil)

	if ok, success := responder.(*opsgraphql.GraphqlPostOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("GraphqlPost failed: responder=%T", responder)
}

// MetaGet 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) MetaGet(params opsmeta.MetaGetParams) (*opsmeta.MetaGetOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.MetaMetaGetHandler == nil {
		return nil, errors.New("metametaget handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "GET", "/v1/meta")
	}

	responder := ws.api.MetaMetaGetHandler.Handle(params, nil)

	if ok, success := responder.(*opsmeta.MetaGetOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("MetaGet failed: responder=%T", responder)
}

// NodesGet 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) NodesGet(params opsnodes.NodesGetParams) (*opsnodes.NodesGetOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.NodesNodesGetHandler == nil {
		return nil, errors.New("nodesnodesget handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "GET", "/v1/nodes")
	}

	responder := ws.api.NodesNodesGetHandler.Handle(params, nil)

	if ok, success := responder.(*opsnodes.NodesGetOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("NodesGet failed: responder=%T", responder)
}

// NodesGetClass 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) NodesGetClass(params opsnodes.NodesGetClassParams) (*opsnodes.NodesGetClassOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.NodesNodesGetClassHandler == nil {
		return nil, errors.New("nodesnodesgetclass handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "GET", "/v1/nodes/{className}")
	}

	responder := ws.api.NodesNodesGetClassHandler.Handle(params, nil)

	if ok, success := responder.(*opsnodes.NodesGetClassOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("NodesGetClass failed: responder=%T", responder)
}

// ObjectsClassDelete 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) ObjectsClassDelete(params opsobjects.ObjectsClassDeleteParams) (*opsobjects.ObjectsClassDeleteNoContent, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.ObjectsObjectsClassDeleteHandler == nil {
		return nil, errors.New("objectsobjectsclassdelete handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "DELETE", "/v1/objects/{className}/{id}")
	}

	responder := ws.api.ObjectsObjectsClassDeleteHandler.Handle(params, nil)

	if ok, success := responder.(*opsobjects.ObjectsClassDeleteNoContent); success {
		return ok, nil
	}

	return nil, fmt.Errorf("ObjectsClassDelete failed: responder=%T", responder)
}

// ObjectsClassGet 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) ObjectsClassGet(params opsobjects.ObjectsClassGetParams) (*opsobjects.ObjectsClassGetOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.ObjectsObjectsClassGetHandler == nil {
		return nil, errors.New("objectsobjectsclassget handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "GET", "/v1/objects/{className}/{id}")
	}

	responder := ws.api.ObjectsObjectsClassGetHandler.Handle(params, nil)

	if ok, success := responder.(*opsobjects.ObjectsClassGetOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("ObjectsClassGet failed: responder=%T", responder)
}

// ObjectsClassHead 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) ObjectsClassHead(params opsobjects.ObjectsClassHeadParams) (*opsobjects.ObjectsClassHeadNoContent, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.ObjectsObjectsClassHeadHandler == nil {
		return nil, errors.New("objectsobjectsclasshead handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "HEAD", "/v1/objects/{className}/{id}")
	}

	responder := ws.api.ObjectsObjectsClassHeadHandler.Handle(params, nil)

	if ok, success := responder.(*opsobjects.ObjectsClassHeadNoContent); success {
		return ok, nil
	}

	return nil, fmt.Errorf("ObjectsClassHead failed: responder=%T", responder)
}

// ObjectsClassPatch 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) ObjectsClassPatch(params opsobjects.ObjectsClassPatchParams) (*opsobjects.ObjectsClassPatchNoContent, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.ObjectsObjectsClassPatchHandler == nil {
		return nil, errors.New("objectsobjectsclasspatch handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "PATCH", "/v1/objects/{className}/{id}")
	}

	responder := ws.api.ObjectsObjectsClassPatchHandler.Handle(params, nil)

	if ok, success := responder.(*opsobjects.ObjectsClassPatchNoContent); success {
		return ok, nil
	}

	return nil, fmt.Errorf("ObjectsClassPatch failed: responder=%T", responder)
}

// ObjectsClassPut 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) ObjectsClassPut(params opsobjects.ObjectsClassPutParams) (*opsobjects.ObjectsClassPutOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.ObjectsObjectsClassPutHandler == nil {
		return nil, errors.New("objectsobjectsclassput handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "PUT", "/v1/objects/{className}/{id}")
	}

	responder := ws.api.ObjectsObjectsClassPutHandler.Handle(params, nil)

	if ok, success := responder.(*opsobjects.ObjectsClassPutOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("ObjectsClassPut failed: responder=%T", responder)
}

// ObjectsClassReferencesCreate 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) ObjectsClassReferencesCreate(params opsobjects.ObjectsClassReferencesCreateParams) (*opsobjects.ObjectsClassReferencesCreateOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.ObjectsObjectsClassReferencesCreateHandler == nil {
		return nil, errors.New("objectsobjectsclassreferencescreate handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "POST", "/v1/objects/{className}/{id}/references/{propertyName}")
	}

	responder := ws.api.ObjectsObjectsClassReferencesCreateHandler.Handle(params, nil)

	if ok, success := responder.(*opsobjects.ObjectsClassReferencesCreateOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("ObjectsClassReferencesCreate failed: responder=%T", responder)
}

// ObjectsClassReferencesDelete 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) ObjectsClassReferencesDelete(params opsobjects.ObjectsClassReferencesDeleteParams) (*opsobjects.ObjectsClassReferencesDeleteNoContent, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.ObjectsObjectsClassReferencesDeleteHandler == nil {
		return nil, errors.New("objectsobjectsclassreferencesdelete handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "DELETE", "/v1/objects/{className}/{id}/references/{propertyName}")
	}

	responder := ws.api.ObjectsObjectsClassReferencesDeleteHandler.Handle(params, nil)

	if ok, success := responder.(*opsobjects.ObjectsClassReferencesDeleteNoContent); success {
		return ok, nil
	}

	return nil, fmt.Errorf("ObjectsClassReferencesDelete failed: responder=%T", responder)
}

// ObjectsClassReferencesPut 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) ObjectsClassReferencesPut(params opsobjects.ObjectsClassReferencesPutParams) (*opsobjects.ObjectsClassReferencesPutOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.ObjectsObjectsClassReferencesPutHandler == nil {
		return nil, errors.New("objectsobjectsclassreferencesput handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "PUT", "/v1/objects/{className}/{id}/references/{propertyName}")
	}

	responder := ws.api.ObjectsObjectsClassReferencesPutHandler.Handle(params, nil)

	if ok, success := responder.(*opsobjects.ObjectsClassReferencesPutOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("ObjectsClassReferencesPut failed: responder=%T", responder)
}

// ObjectsCreate 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) ObjectsCreate(params opsobjects.ObjectsCreateParams) (*opsobjects.ObjectsCreateOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.ObjectsObjectsCreateHandler == nil {
		return nil, errors.New("objectsobjectscreate handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "POST", "/v1/objects")
	}

	responder := ws.api.ObjectsObjectsCreateHandler.Handle(params, nil)

	if ok, success := responder.(*opsobjects.ObjectsCreateOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("ObjectsCreate failed: responder=%T", responder)
}

// ObjectsDelete 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) ObjectsDelete(params opsobjects.ObjectsDeleteParams) (*opsobjects.ObjectsDeleteNoContent, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.ObjectsObjectsDeleteHandler == nil {
		return nil, errors.New("objectsobjectsdelete handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "DELETE", "/v1/objects/{id}")
	}

	responder := ws.api.ObjectsObjectsDeleteHandler.Handle(params, nil)

	if ok, success := responder.(*opsobjects.ObjectsDeleteNoContent); success {
		return ok, nil
	}

	return nil, fmt.Errorf("ObjectsDelete failed: responder=%T", responder)
}

// ObjectsGet 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) ObjectsGet(params opsobjects.ObjectsGetParams) (*opsobjects.ObjectsGetOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.ObjectsObjectsGetHandler == nil {
		return nil, errors.New("objectsobjectsget handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "GET", "/v1/objects/{id}")
	}

	responder := ws.api.ObjectsObjectsGetHandler.Handle(params, nil)

	if ok, success := responder.(*opsobjects.ObjectsGetOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("ObjectsGet failed: responder=%T", responder)
}

// ObjectsHead 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) ObjectsHead(params opsobjects.ObjectsHeadParams) (*opsobjects.ObjectsHeadNoContent, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.ObjectsObjectsHeadHandler == nil {
		return nil, errors.New("objectsobjectshead handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "HEAD", "/v1/objects/{id}")
	}

	responder := ws.api.ObjectsObjectsHeadHandler.Handle(params, nil)

	if ok, success := responder.(*opsobjects.ObjectsHeadNoContent); success {
		return ok, nil
	}

	return nil, fmt.Errorf("ObjectsHead failed: responder=%T", responder)
}

// ObjectsList 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) ObjectsList(params opsobjects.ObjectsListParams) (*opsobjects.ObjectsListOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.ObjectsObjectsListHandler == nil {
		return nil, errors.New("objectsobjectslist handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "GET", "/v1/objects")
	}

	responder := ws.api.ObjectsObjectsListHandler.Handle(params, nil)

	if ok, success := responder.(*opsobjects.ObjectsListOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("ObjectsList failed: responder=%T", responder)
}

// ObjectsPatch 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) ObjectsPatch(params opsobjects.ObjectsPatchParams) (*opsobjects.ObjectsPatchNoContent, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.ObjectsObjectsPatchHandler == nil {
		return nil, errors.New("objectsobjectspatch handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "PATCH", "/v1/objects/{id}")
	}

	responder := ws.api.ObjectsObjectsPatchHandler.Handle(params, nil)

	if ok, success := responder.(*opsobjects.ObjectsPatchNoContent); success {
		return ok, nil
	}

	return nil, fmt.Errorf("ObjectsPatch failed: responder=%T", responder)
}

// ObjectsReferencesCreate 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) ObjectsReferencesCreate(params opsobjects.ObjectsReferencesCreateParams) (*opsobjects.ObjectsReferencesCreateOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.ObjectsObjectsReferencesCreateHandler == nil {
		return nil, errors.New("objectsobjectsreferencescreate handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "POST", "/v1/objects/{id}/references/{propertyName}")
	}

	responder := ws.api.ObjectsObjectsReferencesCreateHandler.Handle(params, nil)

	if ok, success := responder.(*opsobjects.ObjectsReferencesCreateOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("ObjectsReferencesCreate failed: responder=%T", responder)
}

// ObjectsReferencesDelete 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) ObjectsReferencesDelete(params opsobjects.ObjectsReferencesDeleteParams) (*opsobjects.ObjectsReferencesDeleteNoContent, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.ObjectsObjectsReferencesDeleteHandler == nil {
		return nil, errors.New("objectsobjectsreferencesdelete handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "DELETE", "/v1/objects/{id}/references/{propertyName}")
	}

	responder := ws.api.ObjectsObjectsReferencesDeleteHandler.Handle(params, nil)

	if ok, success := responder.(*opsobjects.ObjectsReferencesDeleteNoContent); success {
		return ok, nil
	}

	return nil, fmt.Errorf("ObjectsReferencesDelete failed: responder=%T", responder)
}

// ObjectsReferencesUpdate 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) ObjectsReferencesUpdate(params opsobjects.ObjectsReferencesUpdateParams) (*opsobjects.ObjectsReferencesUpdateOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.ObjectsObjectsReferencesUpdateHandler == nil {
		return nil, errors.New("objectsobjectsreferencesupdate handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "PUT", "/v1/objects/{id}/references/{propertyName}")
	}

	responder := ws.api.ObjectsObjectsReferencesUpdateHandler.Handle(params, nil)

	if ok, success := responder.(*opsobjects.ObjectsReferencesUpdateOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("ObjectsReferencesUpdate failed: responder=%T", responder)
}

// ObjectsUpdate 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) ObjectsUpdate(params opsobjects.ObjectsUpdateParams) (*opsobjects.ObjectsUpdateOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.ObjectsObjectsUpdateHandler == nil {
		return nil, errors.New("objectsobjectsupdate handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "PUT", "/v1/objects/{id}")
	}

	responder := ws.api.ObjectsObjectsUpdateHandler.Handle(params, nil)

	if ok, success := responder.(*opsobjects.ObjectsUpdateOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("ObjectsUpdate failed: responder=%T", responder)
}

// ObjectsValidate 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) ObjectsValidate(params opsobjects.ObjectsValidateParams) (*opsobjects.ObjectsValidateOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.ObjectsObjectsValidateHandler == nil {
		return nil, errors.New("objectsobjectsvalidate handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "POST", "/v1/objects/validate")
	}

	responder := ws.api.ObjectsObjectsValidateHandler.Handle(params, nil)

	if ok, success := responder.(*opsobjects.ObjectsValidateOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("ObjectsValidate failed: responder=%T", responder)
}

// ApplyReplicationScalePlan 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) ApplyReplicationScalePlan(params opsreplication.ApplyReplicationScalePlanParams) (*opsreplication.ApplyReplicationScalePlanOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.ReplicationApplyReplicationScalePlanHandler == nil {
		return nil, errors.New("replicationapplyreplicationscaleplan handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "POST", "/v1/replication/scale")
	}

	responder := ws.api.ReplicationApplyReplicationScalePlanHandler.Handle(params, nil)

	if ok, success := responder.(*opsreplication.ApplyReplicationScalePlanOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("ApplyReplicationScalePlan failed: responder=%T", responder)
}

// CancelReplication 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) CancelReplication(params opsreplication.CancelReplicationParams) (*opsreplication.CancelReplicationNoContent, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.ReplicationCancelReplicationHandler == nil {
		return nil, errors.New("replicationcancelreplication handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "POST", "/v1/replication/replicate/{id}/cancel")
	}

	responder := ws.api.ReplicationCancelReplicationHandler.Handle(params, nil)

	if ok, success := responder.(*opsreplication.CancelReplicationNoContent); success {
		return ok, nil
	}

	return nil, fmt.Errorf("CancelReplication failed: responder=%T", responder)
}

// DeleteAllReplications 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) DeleteAllReplications(params opsreplication.DeleteAllReplicationsParams) (*opsreplication.DeleteAllReplicationsNoContent, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.ReplicationDeleteAllReplicationsHandler == nil {
		return nil, errors.New("replicationdeleteallreplications handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "DELETE", "/v1/replication/replicate")
	}

	responder := ws.api.ReplicationDeleteAllReplicationsHandler.Handle(params, nil)

	if ok, success := responder.(*opsreplication.DeleteAllReplicationsNoContent); success {
		return ok, nil
	}

	return nil, fmt.Errorf("DeleteAllReplications failed: responder=%T", responder)
}

// DeleteReplication 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) DeleteReplication(params opsreplication.DeleteReplicationParams) (*opsreplication.DeleteReplicationNoContent, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.ReplicationDeleteReplicationHandler == nil {
		return nil, errors.New("replicationdeletereplication handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "DELETE", "/v1/replication/replicate/{id}")
	}

	responder := ws.api.ReplicationDeleteReplicationHandler.Handle(params, nil)

	if ok, success := responder.(*opsreplication.DeleteReplicationNoContent); success {
		return ok, nil
	}

	return nil, fmt.Errorf("DeleteReplication failed: responder=%T", responder)
}

// ForceDeleteReplications 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) ForceDeleteReplications(params opsreplication.ForceDeleteReplicationsParams) (*opsreplication.ForceDeleteReplicationsOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.ReplicationForceDeleteReplicationsHandler == nil {
		return nil, errors.New("replicationforcedeletereplications handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "POST", "/v1/replication/replicate/force-delete")
	}

	responder := ws.api.ReplicationForceDeleteReplicationsHandler.Handle(params, nil)

	if ok, success := responder.(*opsreplication.ForceDeleteReplicationsOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("ForceDeleteReplications failed: responder=%T", responder)
}

// GetCollectionShardingState 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) GetCollectionShardingState(params opsreplication.GetCollectionShardingStateParams) (*opsreplication.GetCollectionShardingStateOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.ReplicationGetCollectionShardingStateHandler == nil {
		return nil, errors.New("replicationgetcollectionshardingstate handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "GET", "/v1/replication/sharding-state")
	}

	responder := ws.api.ReplicationGetCollectionShardingStateHandler.Handle(params, nil)

	if ok, success := responder.(*opsreplication.GetCollectionShardingStateOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("GetCollectionShardingState failed: responder=%T", responder)
}

// GetReplicationScalePlan 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) GetReplicationScalePlan(params opsreplication.GetReplicationScalePlanParams) (*opsreplication.GetReplicationScalePlanOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.ReplicationGetReplicationScalePlanHandler == nil {
		return nil, errors.New("replicationgetreplicationscaleplan handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "GET", "/v1/replication/scale")
	}

	responder := ws.api.ReplicationGetReplicationScalePlanHandler.Handle(params, nil)

	if ok, success := responder.(*opsreplication.GetReplicationScalePlanOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("GetReplicationScalePlan failed: responder=%T", responder)
}

// ListReplication 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) ListReplication(params opsreplication.ListReplicationParams) (*opsreplication.ListReplicationOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.ReplicationListReplicationHandler == nil {
		return nil, errors.New("replicationlistreplication handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "GET", "/v1/replication/replicate/list")
	}

	responder := ws.api.ReplicationListReplicationHandler.Handle(params, nil)

	if ok, success := responder.(*opsreplication.ListReplicationOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("ListReplication failed: responder=%T", responder)
}

// Replicate 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) Replicate(params opsreplication.ReplicateParams) (*opsreplication.ReplicateOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.ReplicationReplicateHandler == nil {
		return nil, errors.New("replicationreplicate handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "POST", "/v1/replication/replicate")
	}

	responder := ws.api.ReplicationReplicateHandler.Handle(params, nil)

	if ok, success := responder.(*opsreplication.ReplicateOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("Replicate failed: responder=%T", responder)
}

// ReplicationDetails 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) ReplicationDetails(params opsreplication.ReplicationDetailsParams) (*opsreplication.ReplicationDetailsOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.ReplicationReplicationDetailsHandler == nil {
		return nil, errors.New("replicationreplicationdetails handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "GET", "/v1/replication/replicate/{id}")
	}

	responder := ws.api.ReplicationReplicationDetailsHandler.Handle(params, nil)

	if ok, success := responder.(*opsreplication.ReplicationDetailsOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("ReplicationDetails failed: responder=%T", responder)
}

// AliasesCreate 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) AliasesCreate(params opsschema.AliasesCreateParams) (*opsschema.AliasesCreateOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.SchemaAliasesCreateHandler == nil {
		return nil, errors.New("schemaaliasescreate handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "POST", "/v1/aliases")
	}

	responder := ws.api.SchemaAliasesCreateHandler.Handle(params, nil)

	if ok, success := responder.(*opsschema.AliasesCreateOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("AliasesCreate failed: responder=%T", responder)
}

// AliasesDelete 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) AliasesDelete(params opsschema.AliasesDeleteParams) (*opsschema.AliasesDeleteNoContent, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.SchemaAliasesDeleteHandler == nil {
		return nil, errors.New("schemaaliasesdelete handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "DELETE", "/v1/aliases/{aliasName}")
	}

	responder := ws.api.SchemaAliasesDeleteHandler.Handle(params, nil)

	if ok, success := responder.(*opsschema.AliasesDeleteNoContent); success {
		return ok, nil
	}

	return nil, fmt.Errorf("AliasesDelete failed: responder=%T", responder)
}

// AliasesGet 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) AliasesGet(params opsschema.AliasesGetParams) (*opsschema.AliasesGetOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.SchemaAliasesGetHandler == nil {
		return nil, errors.New("schemaaliasesget handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "GET", "/v1/aliases")
	}

	responder := ws.api.SchemaAliasesGetHandler.Handle(params, nil)

	if ok, success := responder.(*opsschema.AliasesGetOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("AliasesGet failed: responder=%T", responder)
}

// AliasesGetAlias 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) AliasesGetAlias(params opsschema.AliasesGetAliasParams) (*opsschema.AliasesGetAliasOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.SchemaAliasesGetAliasHandler == nil {
		return nil, errors.New("schemaaliasesgetalias handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "GET", "/v1/aliases/{aliasName}")
	}

	responder := ws.api.SchemaAliasesGetAliasHandler.Handle(params, nil)

	if ok, success := responder.(*opsschema.AliasesGetAliasOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("AliasesGetAlias failed: responder=%T", responder)
}

// AliasesUpdate 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) AliasesUpdate(params opsschema.AliasesUpdateParams) (*opsschema.AliasesUpdateOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.SchemaAliasesUpdateHandler == nil {
		return nil, errors.New("schemaaliasesupdate handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "PUT", "/v1/aliases/{aliasName}")
	}

	responder := ws.api.SchemaAliasesUpdateHandler.Handle(params, nil)

	if ok, success := responder.(*opsschema.AliasesUpdateOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("AliasesUpdate failed: responder=%T", responder)
}

// SchemaDump 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) SchemaDump(params opsschema.SchemaDumpParams) (*opsschema.SchemaDumpOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.SchemaSchemaDumpHandler == nil {
		return nil, errors.New("schemaschemadump handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "GET", "/v1/schema")
	}

	responder := ws.api.SchemaSchemaDumpHandler.Handle(params, nil)

	if ok, success := responder.(*opsschema.SchemaDumpOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("SchemaDump failed: responder=%T", responder)
}

// SchemaObjectsCreate 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) SchemaObjectsCreate(params opsschema.SchemaObjectsCreateParams) (*opsschema.SchemaObjectsCreateOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.SchemaSchemaObjectsCreateHandler == nil {
		return nil, errors.New("schemaschemaobjectscreate handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "POST", "/v1/schema")
	}

	responder := ws.api.SchemaSchemaObjectsCreateHandler.Handle(params, nil)

	if ok, success := responder.(*opsschema.SchemaObjectsCreateOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("SchemaObjectsCreate failed: responder=%T", responder)
}

// SchemaObjectsDelete 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) SchemaObjectsDelete(params opsschema.SchemaObjectsDeleteParams) (*opsschema.SchemaObjectsDeleteOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.SchemaSchemaObjectsDeleteHandler == nil {
		return nil, errors.New("schemaschemaobjectsdelete handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "DELETE", "/v1/schema/{className}")
	}

	responder := ws.api.SchemaSchemaObjectsDeleteHandler.Handle(params, nil)

	if ok, success := responder.(*opsschema.SchemaObjectsDeleteOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("SchemaObjectsDelete failed: responder=%T", responder)
}

// SchemaObjectsGet 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) SchemaObjectsGet(params opsschema.SchemaObjectsGetParams) (*opsschema.SchemaObjectsGetOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.SchemaSchemaObjectsGetHandler == nil {
		return nil, errors.New("schemaschemaobjectsget handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "GET", "/v1/schema/{className}")
	}

	responder := ws.api.SchemaSchemaObjectsGetHandler.Handle(params, nil)

	if ok, success := responder.(*opsschema.SchemaObjectsGetOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("SchemaObjectsGet failed: responder=%T", responder)
}

// SchemaObjectsPropertiesAdd 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) SchemaObjectsPropertiesAdd(params opsschema.SchemaObjectsPropertiesAddParams) (*opsschema.SchemaObjectsPropertiesAddOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.SchemaSchemaObjectsPropertiesAddHandler == nil {
		return nil, errors.New("schemaschemaobjectspropertiesadd handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "POST", "/v1/schema/{className}/properties")
	}

	responder := ws.api.SchemaSchemaObjectsPropertiesAddHandler.Handle(params, nil)

	if ok, success := responder.(*opsschema.SchemaObjectsPropertiesAddOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("SchemaObjectsPropertiesAdd failed: responder=%T", responder)
}

// SchemaObjectsPropertiesDelete 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) SchemaObjectsPropertiesDelete(params opsschema.SchemaObjectsPropertiesDeleteParams) (*opsschema.SchemaObjectsPropertiesDeleteOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.SchemaSchemaObjectsPropertiesDeleteHandler == nil {
		return nil, errors.New("schemaschemaobjectspropertiesdelete handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "DELETE", "/v1/schema/{className}/properties/{propertyName}/index/{indexName}")
	}

	responder := ws.api.SchemaSchemaObjectsPropertiesDeleteHandler.Handle(params, nil)

	if ok, success := responder.(*opsschema.SchemaObjectsPropertiesDeleteOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("SchemaObjectsPropertiesDelete failed: responder=%T", responder)
}

// SchemaObjectsShardsGet 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) SchemaObjectsShardsGet(params opsschema.SchemaObjectsShardsGetParams) (*opsschema.SchemaObjectsShardsGetOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.SchemaSchemaObjectsShardsGetHandler == nil {
		return nil, errors.New("schemaschemaobjectsshardsget handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "GET", "/v1/schema/{className}/shards")
	}

	responder := ws.api.SchemaSchemaObjectsShardsGetHandler.Handle(params, nil)

	if ok, success := responder.(*opsschema.SchemaObjectsShardsGetOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("SchemaObjectsShardsGet failed: responder=%T", responder)
}

// SchemaObjectsShardsUpdate 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) SchemaObjectsShardsUpdate(params opsschema.SchemaObjectsShardsUpdateParams) (*opsschema.SchemaObjectsShardsUpdateOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.SchemaSchemaObjectsShardsUpdateHandler == nil {
		return nil, errors.New("schemaschemaobjectsshardsupdate handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "PUT", "/v1/schema/{className}/shards/{shardName}")
	}

	responder := ws.api.SchemaSchemaObjectsShardsUpdateHandler.Handle(params, nil)

	if ok, success := responder.(*opsschema.SchemaObjectsShardsUpdateOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("SchemaObjectsShardsUpdate failed: responder=%T", responder)
}

// SchemaObjectsUpdate 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) SchemaObjectsUpdate(params opsschema.SchemaObjectsUpdateParams) (*opsschema.SchemaObjectsUpdateOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.SchemaSchemaObjectsUpdateHandler == nil {
		return nil, errors.New("schemaschemaobjectsupdate handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "PUT", "/v1/schema/{className}")
	}

	responder := ws.api.SchemaSchemaObjectsUpdateHandler.Handle(params, nil)

	if ok, success := responder.(*opsschema.SchemaObjectsUpdateOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("SchemaObjectsUpdate failed: responder=%T", responder)
}

// TenantExists 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) TenantExists(params opsschema.TenantExistsParams) (*opsschema.TenantExistsOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.SchemaTenantExistsHandler == nil {
		return nil, errors.New("schematenantexists handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "HEAD", "/v1/schema/{className}/tenants/{tenantName}")
	}

	responder := ws.api.SchemaTenantExistsHandler.Handle(params, nil)

	if ok, success := responder.(*opsschema.TenantExistsOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("TenantExists failed: responder=%T", responder)
}

// TenantsCreate 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) TenantsCreate(params opsschema.TenantsCreateParams) (*opsschema.TenantsCreateOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.SchemaTenantsCreateHandler == nil {
		return nil, errors.New("schematenantscreate handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "POST", "/v1/schema/{className}/tenants")
	}

	responder := ws.api.SchemaTenantsCreateHandler.Handle(params, nil)

	if ok, success := responder.(*opsschema.TenantsCreateOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("TenantsCreate failed: responder=%T", responder)
}

// TenantsDelete 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) TenantsDelete(params opsschema.TenantsDeleteParams) (*opsschema.TenantsDeleteOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.SchemaTenantsDeleteHandler == nil {
		return nil, errors.New("schematenantsdelete handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "DELETE", "/v1/schema/{className}/tenants")
	}

	responder := ws.api.SchemaTenantsDeleteHandler.Handle(params, nil)

	if ok, success := responder.(*opsschema.TenantsDeleteOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("TenantsDelete failed: responder=%T", responder)
}

// TenantsGet 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) TenantsGet(params opsschema.TenantsGetParams) (*opsschema.TenantsGetOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.SchemaTenantsGetHandler == nil {
		return nil, errors.New("schematenantsget handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "GET", "/v1/schema/{className}/tenants")
	}

	responder := ws.api.SchemaTenantsGetHandler.Handle(params, nil)

	if ok, success := responder.(*opsschema.TenantsGetOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("TenantsGet failed: responder=%T", responder)
}

// TenantsGetOne 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) TenantsGetOne(params opsschema.TenantsGetOneParams) (*opsschema.TenantsGetOneOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.SchemaTenantsGetOneHandler == nil {
		return nil, errors.New("schematenantsgetone handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "GET", "/v1/schema/{className}/tenants/{tenantName}")
	}

	responder := ws.api.SchemaTenantsGetOneHandler.Handle(params, nil)

	if ok, success := responder.(*opsschema.TenantsGetOneOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("TenantsGetOne failed: responder=%T", responder)
}

// TenantsUpdate 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) TenantsUpdate(params opsschema.TenantsUpdateParams) (*opsschema.TenantsUpdateOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.SchemaTenantsUpdateHandler == nil {
		return nil, errors.New("schematenantsupdate handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "PUT", "/v1/schema/{className}/tenants")
	}

	responder := ws.api.SchemaTenantsUpdateHandler.Handle(params, nil)

	if ok, success := responder.(*opsschema.TenantsUpdateOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("TenantsUpdate failed: responder=%T", responder)
}

// ActivateUser 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) ActivateUser(params opsusers.ActivateUserParams) (*opsusers.ActivateUserOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.UsersActivateUserHandler == nil {
		return nil, errors.New("usersactivateuser handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "POST", "/v1/users/db/{user_id}/activate")
	}

	responder := ws.api.UsersActivateUserHandler.Handle(params, nil)

	if ok, success := responder.(*opsusers.ActivateUserOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("ActivateUser failed: responder=%T", responder)
}

// CreateUser 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) CreateUser(params opsusers.CreateUserParams) (*opsusers.CreateUserCreated, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.UsersCreateUserHandler == nil {
		return nil, errors.New("userscreateuser handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "POST", "/v1/users/db/{user_id}")
	}

	responder := ws.api.UsersCreateUserHandler.Handle(params, nil)

	if ok, success := responder.(*opsusers.CreateUserCreated); success {
		return ok, nil
	}

	return nil, fmt.Errorf("CreateUser failed: responder=%T", responder)
}

// DeactivateUser 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) DeactivateUser(params opsusers.DeactivateUserParams) (*opsusers.DeactivateUserOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.UsersDeactivateUserHandler == nil {
		return nil, errors.New("usersdeactivateuser handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "POST", "/v1/users/db/{user_id}/deactivate")
	}

	responder := ws.api.UsersDeactivateUserHandler.Handle(params, nil)

	if ok, success := responder.(*opsusers.DeactivateUserOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("DeactivateUser failed: responder=%T", responder)
}

// DeleteUser 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) DeleteUser(params opsusers.DeleteUserParams) (*opsusers.DeleteUserNoContent, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.UsersDeleteUserHandler == nil {
		return nil, errors.New("usersdeleteuser handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "DELETE", "/v1/users/db/{user_id}")
	}

	responder := ws.api.UsersDeleteUserHandler.Handle(params, nil)

	if ok, success := responder.(*opsusers.DeleteUserNoContent); success {
		return ok, nil
	}

	return nil, fmt.Errorf("DeleteUser failed: responder=%T", responder)
}

// GetOwnInfo 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) GetOwnInfo(params opsusers.GetOwnInfoParams) (*opsusers.GetOwnInfoOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.UsersGetOwnInfoHandler == nil {
		return nil, errors.New("usersgetowninfo handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "GET", "/v1/users/own-info")
	}

	responder := ws.api.UsersGetOwnInfoHandler.Handle(params, nil)

	if ok, success := responder.(*opsusers.GetOwnInfoOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("GetOwnInfo failed: responder=%T", responder)
}

// GetUserInfo 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) GetUserInfo(params opsusers.GetUserInfoParams) (*opsusers.GetUserInfoOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.UsersGetUserInfoHandler == nil {
		return nil, errors.New("usersgetuserinfo handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "GET", "/v1/users/db/{user_id}")
	}

	responder := ws.api.UsersGetUserInfoHandler.Handle(params, nil)

	if ok, success := responder.(*opsusers.GetUserInfoOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("GetUserInfo failed: responder=%T", responder)
}

// ListAllUsers 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) ListAllUsers(params opsusers.ListAllUsersParams) (*opsusers.ListAllUsersOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.UsersListAllUsersHandler == nil {
		return nil, errors.New("userslistallusers handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "GET", "/v1/users/db")
	}

	responder := ws.api.UsersListAllUsersHandler.Handle(params, nil)

	if ok, success := responder.(*opsusers.ListAllUsersOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("ListAllUsers failed: responder=%T", responder)
}

// RotateUserAPIKey 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) RotateUserAPIKey(params opsusers.RotateUserAPIKeyParams) (*opsusers.RotateUserAPIKeyOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.UsersRotateUserAPIKeyHandler == nil {
		return nil, errors.New("usersrotateuserapikey handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "POST", "/v1/users/db/{user_id}/rotate-key")
	}

	responder := ws.api.UsersRotateUserAPIKeyHandler.Handle(params, nil)

	if ok, success := responder.(*opsusers.RotateUserAPIKeyOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("RotateUserAPIKey failed: responder=%T", responder)
}

// GetWellKnownOpenidConfiguration 直接使用 REST operation 参数，绕过 HTTP 路由绑定。
func (ws *WeaviateServer) GetWellKnownOpenidConfiguration(params opswell_known.GetWellKnownOpenidConfigurationParams) (*opswell_known.GetWellKnownOpenidConfigurationOK, error) {
	if ws == nil || ws.api == nil {
		return nil, errors.New("weaviate server is not initialized")
	}
	if ws.api.WellKnownGetWellKnownOpenidConfigurationHandler == nil {
		return nil, errors.New("wellknowngetwellknownopenidconfiguration handler is not configured")
	}
	if params.HTTPRequest == nil {
		params.HTTPRequest = newInProcessRequest(nil, "GET", "/v1/.well-known/openid-configuration")
	}

	responder := ws.api.WellKnownGetWellKnownOpenidConfigurationHandler.Handle(params, nil)

	if ok, success := responder.(*opswell_known.GetWellKnownOpenidConfigurationOK); success {
		return ok, nil
	}

	return nil, fmt.Errorf("GetWellKnownOpenidConfiguration failed: responder=%T", responder)
}
